### ISSUE TITLE
Problem getting resource: Failed to fetch

### ISSUE THREAD

**Issue by eladisimo** [uncodead/BrewUNO#105]
I've built a setup with only wemos D1, power supply (steady, ~5.1v that can hold upto 3A), and a switch to start testing it. 
when executing START BOIL and many other cases, the device reboots spontaneously. 

I've tested this with several different devices and power supplies and all behave the same. 

any ideas?

**Comment by uncodead** [comment]
double check in the wiring diagram

**Comment by eladisimo** [comment]
Thanks.
I have and its correct.
I switched to thinner wires and the problem is gone.
