### ISSUE TITLE
There is no sensor adjustment function.

### ISSUE THREAD

**Issue by paulopro** [uncodead/BrewUNO#12]
I have 3 sensors used on BrewManiac and the 3 needed adjustments.

**Comment by uncodead** [comment]
Paulo, can you explain how would you like to do this adjustments?

**Comment by paulopro** [comment]
bom dia Bruno, seria semelhante ao BrewManiac, não sou bom em programação em C, apenas programo CLPs, mas eu colocaria um campo na tela de ajustes pra fazer esse ajuste, teria que ser uma variavel que permitisse escrever valores negativos, ai na logica seria somado ao valor real lido do sensor.

**Comment by paulopro** [comment]
![Logica](https://user-images.githubusercontent.com/54174759/63172190-80d70e80-c013-11e9-8b4b-c65e36189f8c.jpg)

**Comment by uncodead** [comment]
Entendi, vou fazer! Voce me ajuda testar?
Abs

**Comment by paulopro** [comment]
se der tempo sim, ainda não migrei meu brew, mas conheço uma pessoa que pode testar rápido!

**Comment by uncodead** [comment]
Criei duas opções para calibrar o sensor:

![image](https://user-images.githubusercontent.com/181846/63226396-6fc30480-c1af-11e9-8fef-7d423598c315.png)

Pode testar por favor? Obrigado
