### ISSUE TITLE
Enable the use of 5 sensors and allow to choose the sensor in each step.

### ISSUE THREAD

**Issue by paulopro** [uncodead/BrewUNO#13]
Example:
![image](https://user-images.githubusercontent.com/54174759/63177226-d57f8700-c01d-11e9-906c-39df1c5b389c.png)

**Comment by uncodead** [comment]
at 0.0.10 branch, you cna choose up to 5 sensors.
but i didnt implement the heat control yet

**Comment by uncodead** [comment]
Resolved at 1.0.01 version
