### ISSUE TITLE
beta info display and lock state below pump status

### ISSUE THREAD

**Issue by rampanelli** [uncodead/BrewUNO#16]
![beta_info](https://user-images.githubusercontent.com/26370251/63228926-d4db2200-c1d0-11e9-83e7-552d54997de8.jpeg)

**Comment by uncodead** [comment]
qual seria a alteração? nao entendi... descreve a mudança.

abs

**Comment by uncodead** [comment]
acho que no contador fica mais visível... e indica que o tempo esta 'locado'.  Se colocar na linha de baixo parece algo relacionado a resistência. 

Obs.: Seu código gera overhead na renderização do display. Tente renderizar linha por linha.
