### ISSUE TITLE
Don't work on AP mode

### ISSUE THREAD

**Issue by rampanelli** [uncodead/BrewUNO#22]
System does not work on AP mode, time counter bug.

![p1](https://user-images.githubusercontent.com/26370251/64923079-d4707f80-d7ac-11e9-9da3-a5c7c74ff68c.jpg)

**Comment by rampanelli** [comment]
But display LCD timer counter works, why?

![p2](https://user-images.githubusercontent.com/26370251/64923120-4052e800-d7ad-11e9-9420-c07a8445364f.jpeg)

**Comment by rampanelli** [comment]
![p3](https://user-images.githubusercontent.com/26370251/64923193-f585a000-d7ad-11e9-899a-b52b424f24cd.jpeg)
![p4](https://user-images.githubusercontent.com/26370251/64923194-f585a000-d7ad-11e9-94fa-888d44c570d9.jpeg)

**Comment by uncodead** [comment]
Resolved at 1.0.01 version
