### ISSUE TITLE
Resistencia para fervura

### ISSUE THREAD

**Issue by IcaroMC** [uncodead/BrewUNO#32]
Acionamento de outro relê para resistência em outra panela para fervura.

**Comment by rampanelli** [comment]
A versão atual (1.0.06) suporta panela de fervura em separado no pino D4, falta documentar o recurso mas já foi testado por mim utilizando um driver composto por transistor PNP.  Ainda estamos discutindo e  estudando como implementar funcionamento simultâneo com outros passos.

**Comment by rampanelli** [comment]
![b1a](https://user-images.githubusercontent.com/26370251/67791342-059fc900-fa56-11e9-925b-dff079e36744.jpeg)
![b1d](https://user-images.githubusercontent.com/26370251/67791349-08022300-fa56-11e9-99d6-3b9572ff1016.jpeg)

Boil pelo pino D4 usando o driver com transistor PNP.

**Comment by IcaroMC** [comment]
Fala Luciano, boa tarde!

Top demais, onde consigo essa plaquinha top? O meu fui eu mesmo que montei
então não tem placa. e está sem o teclado.

Estou montando a minha Tina de fervura e já quero usar essa belezura.

Obrigado pelo contato.

Em ter, 29 de out de 2019 às 14:12, Luciano Rampanelli <
notifications@github.com> escreveu:

**Comment by uncodead** [comment]
Vou fechar essa Issue. A versao atual do sistema contempla saida para resistencia de fervura no D4
