### ISSUE TITLE
Erro de comunicação

### ISSUE THREAD

**Issue by aureliotornisiello** [uncodead/BrewUNO#35]
olá, instalei a versão1.0.07, faz a conexão, mas depois começa a dar erro na conexão, voltei para a versão 1.0.02 e está funcionando perfeitamente, o que pode estar ocorrendo?

**Comment by uncodead** [comment]
Tenta novamente com a versao do bin

**Comment by aureliotornisiello** [comment]
Reinstalei com a versão do bin que está no repositório. Conecta e funciona alguns minutos depois ao fazer qualquer alteração dá erro de comunicação.

**Comment by dumpamob** [comment]
Pegou os últimos binários que foram colocados hoje após o almoço, pelas 13h? Estou na segunda simulação real aqui e não tive problema algum.

**Comment by aureliotornisiello** [comment]
sim peguei os ultimos binarios, o erro somente ocorre quando vou colocar a senha do wifi aqui de casa, ai não funciona mais.... Enquanto não coloco a rede wifi está funcionando (somente o tempo não está andando na tela)

**Comment by uncodead** [comment]
O wemos reinicia?

**Comment by aureliotornisiello** [comment]
sim, limpei antes de gravar. Mesmo reiniciando aparece a tela e qualquer acionamento ou setting dá erro "Falha ao procurar".  Mas fica dificil a conexão mesmo desligando e ligando.

**Comment by uncodead** [comment]
Você reparou se o LCD pisca?

**Comment by aureliotornisiello** [comment]
Não estou usando LCD. Depois que trava não aparece a rede BrewUno

**Comment by uncodead** [comment]
Parece que tem alguma coisa resetando seu brewuno

**Comment by aureliotornisiello** [comment]
![IMG_20191029_225852678](https://user-images.githubusercontent.com/57144891/67823239-0dd12600-faa1-11e9-8361-ba0b11d8ec8a.jpg)
![IMG_20191029_230500182_BURST000_COVER_TOP](https://user-images.githubusercontent.com/57144891/67823240-0dd12600-faa1-11e9-8893-c8a262e754b5.jpg)
![IMG_20191029_230508736](https://user-images.githubusercontent.com/57144891/67823241-0dd12600-faa1-11e9-8f3a-4a62042674d2.jpg)
![IMG_20191029_230521184](https://user-images.githubusercontent.com/57144891/67823242-0e69bc80-faa1-11e9-9a89-61666ae1fa65.jpg)

**Comment by aureliotornisiello** [comment]
fiz outros testes. Desliguei minha wifi, com muito custo consegui conectar e funcionou. No status da conexão estava IDLE, liguei meu wifi e pedi para procurar e quando conectei a mensagem estava "disconected" depois começou a novamente a falha de comunicação.
![IMG_20191029_232025378](https://user-images.githubusercontent.com/57144891/67824053-0c552d00-faa4-11e9-9702-2d3671166c67.jpg)
![IMG_20191029_232636162](https://user-images.githubusercontent.com/57144891/67824055-0cedc380-faa4-11e9-94ab-b66c8664edc6.jpg)

**Comment by uncodead** [comment]
Tenta em outra rede. Testa com essa branch:
https://github.com/uncodead/BrewUNO/tree/interface_cache

**Comment by aureliotornisiello** [comment]
OI testei está nova versão e mesmo problemas de comunicação (agora o  gráfico de temperatura sumiu). Voltei com a versão com final .2 e funcionando correto

**Comment by uncodead** [comment]
Essa versao que vc pegou eu retirei o grafico mesmo. mas e muito estranho esse problema de comunicacao. Nao consigo simular.

**Comment by uncodead** [comment]
Se mantém com a 02. Estou investigando.

Em qua, 30 de out de 2019 22:48, aureliotornisiello <
notifications@github.com> escreveu:

**Comment by aureliotornisiello** [comment]
ok obrigado pelo retorno, quando vc quiser faço os testes.

**Comment by rampanelli** [comment]
Aurelio testa com estes binários! 
https://github.com/rampanelli/BrewUNO/tree/master/bin
