### ISSUE TITLE
Mostrar a versão do código na aba "Sobre".

### ISSUE THREAD

**Issue by ViniciusBTavares** [uncodead/BrewUNO#36]
Poderia mostrar a versão do código na aba "Sobre" e também notas sobre as últimas atualizações.

**Comment by ViniciusBTavares** [comment]
Isso ajudaria a ver se a gravação da memória flash foi bem sucedida. Posso estar enganado, mas não consegui encontrar a versão em outro lugar!

**Comment by uncodead** [comment]
Feito, mas é preciso entrar na tela principal para carregar o status (temperatura, etc) do wemos (5 segundos). Isso foi feito dessa forma para evitar uma chamada no wemos desnecessária para uma informação que ja tem no log.
