### ISSUE TITLE
Travamentos e perdd pacotes na rede v1.0.08

### ISSUE THREAD

**Issue by rampanelli** [uncodead/BrewUNO#38]
Ocorre travamento e perda de pacotes na rede local somente quando algum processo esta rodando (mash/boil), tornando a interface instável, não atualiza e não mostra status corretamente mesmo esperando vários segundos, até um minuto. No entanto ao efetuar uma pausa no processo ou cancelar o processo, todos os campos voltam a atualizar normalmente, cessam as perdas de pacotes na rede e a interface fica novamente responsiva aos clicks e atualizações. Fiz um vídeo e enviei no privado pois aqui só é possível publicar imagens.

**Comment by uncodead** [comment]
Vi o vídeo e chegamos a conclusão que o travamento descrito refere-se aos 5 segundos de delay que a interface tem para atualizar. Esse tempo é necessário para não sobrecarregar o wemos e causar 'reset'. Futuramente vou melhorar o consumo de memória e diminuir esse delay. Tradeoff de funcionalidades e performance com o microcontrolador wemos d1.
