### ISSUE TITLE
Na última versão o SSID está com nome "ssid" e não como "BrewUNO"

### ISSUE THREAD

**Issue by ViniciusBTavares** [uncodead/BrewUNO#39]
Na última versão o SSID está com nome "ssid" e não como "BrewUNO".

**Comment by uncodead** [comment]
Você fez upload do FileSystem?

Em qua., 13 de nov. de 2019 às 10:39, Vinicius Tavares <
notifications@github.com> escreveu:

**Comment by ViniciusBTavares** [comment]
Gravei novamente e agora deu certo! Provavelmente foi isso mesmo! Desculpe e Obrigado.
