### ISSUE TITLE
Sugestões para implementações

### ISSUE THREAD

**Issue by rampanelli** [uncodead/BrewUNO#40]
- preparação para suportar plugins
- controle de receitas/salvar/imprimir/executar
- powermeter baseado nas características do equipamento (sem sensores)
- controle de fermentação
- controle de torneiras
- integração com ispindel/plaato e outros hardwares
- controle de atores adicionais para acionamento de válvulas e outros acessórios inclusive por grupo.
- controle de resfriamento integrado
- botões para acionamento de GPIO manual permitindo diversas utilizações
- log detalhado da brassagem incluindo resumo da receita e gráfico de temperaturas
- controle para destilação

**Comment by rampanelli** [comment]
Exemplo:
![example](https://user-images.githubusercontent.com/26370251/68893138-43157f00-0703-11ea-9d43-9145dd4145e6.jpeg)

- log detalhado da brassagem incluindo resumo da receita e gráfico de temperaturas

**Comment by uncodead** [comment]
Não é o foco do projeto nesse momento. Talvez no futuro.
