### ISSUE TITLE
Aumentar o Tempo na Sacarificação

### ISSUE THREAD

**Issue by IcaroMC** [uncodead/BrewUNO#42]
Teria como colocar uma opção de aumentar o tempo da rampa para quando for feito o teste de iodo e não tenha convertido poder adicionar mais tempo.

**Comment by rampanelli** [comment]
Ative a checkbox "Step Lock" no último passo anterior ao MashOut e o sistema permanecerá nesse passo até que seja feito o avanço manualmente. Anote o tempo total necessário e atualize a receita para a próxima vez.

**Comment by IcaroMC** [comment]
Entendi! Controle manual! Obrigado....

Em seg., 9 de dez. de 2019 às 12:06, Luciano Rampanelli <
notifications@github.com> escreveu:

**Comment by paulopro** [comment]
acho que seria interessante um botão de increase / decrease time, ja fixado em 5 minutos, assim vc poderia apenas somar ao tempo do step ja configurado , porem aessa ação deveria estar habilitada ate no maximo 5 minutos pra terminar o step, assim não teria problema com o temporizador

**Comment by IcaroMC** [comment]
> acho que seria interessante um botão de increase / decrease time, ja fixado em 5 minutos, assim vc poderia apenas somar ao tempo do step ja configurado , porem aessa ação deveria estar habilitada ate no maximo 5 minutos pra terminar o step, assim não teria problema com o temporizador

É isso ai meu amigo Paulo!
