### ISSUE TITLE
Pump pre mash

### ISSUE THREAD

**Issue by zacvid** [uncodead/BrewUNO#48]
Hi Bruno, I've been using BrewUNO for 1 month, I'm really enjoying it, but I found an error in the mash. When I start the pre mash I leave the pump off but it turns on anyway. I asked a friend who is a programmer to take a look and see if the problem was solved.

Keep the MashService.cpp file, line 40,  like this:

         // _pump-> TurnPumpOn ();
         activeStatus-> Recirculation = ((int) steps [0] ["r"]) == 1;
         if (activeStatus-> Recirculation)
             _pump-> TurnPumpOn ();
         else
             _pump-> TurnPumpOff ();

Do you intend to save recipes on BrewUNO?

Regards,
Zac

**Comment by uncodead** [comment]
Resolved the pump issue.
I'll work on save recipe ASAP. Thanks.
