### ISSUE TITLE
CORREÇÃO PARA VALORES DE OFFSET E SELEÇÃO DE SENSOR DURANTE A FERVURA

### ISSUE THREAD

**Issue by rampanelli** [uncodead/BrewUNO#51]
in file: BrewUNO\src\BoilKettleHeaterService.cpp

void BoilKettleHeaterService::SetUP()
{
  _activeStatus->EnableBoilKettle = _brewSettingsService->EnableBoilKettle;
  _activeStatus->BoilTargetTemperature = _brewSettingsService->BoilTemperature;
  //if (!_activeStatus->EnableBoilKettle)
  //  _activeStatus->BoilTemperature = _activeStatus->Temperature;
        if (!_brewSettingsService->EnableBoilKettle) {
            _activeStatus->BoilSensor = _brewSettingsService->MainSensor;
            _activeStatus->BoilTemperature = _activeStatus->Temperature;
        } else {
            _activeStatus->BoilSensor = _brewSettingsService->BoilSensor;
        }
}

**Comment by uncodead** [comment]
Nao entendi o erro e não pude reproduzir. Possivelmente corrigido na versão 15.
