### ISSUE TITLE
Controlo de mais bombas

### ISSUE THREAD

**Issue by KaYs3r** [uncodead/BrewUNO#57]
Já que é possível ter as 3 panelas configuradas, penso que seria útil poder adicionar mais bombas. 
No meu caso tenho uma bomba em cada panela.

**Comment by uncodead** [comment]
O wemos nao tem mais saidas... so na pcf

Em qua., 22 de jul. de 2020 às 23:12, KaYs3r <notifications@github.com>
escreveu:

**Comment by KaYs3r** [comment]
@uncodead o wemos não, mas outras placas compatíveis sim, por exemplo as NodeMCU. :)
Parabéns pelo projecto.

**Comment by uncodead** [comment]
o nodemcu tem a mesma quantidades de portas que o wemos :/

**Comment by KaYs3r** [comment]
@uncodead desculpa, tens razão. Como vi que tem muitos mais pinos, pensei que tinha mais GPIOs. 
Sim, era boa ideia usar as saídas livres da PCF.
Se não quiseres obrigar a usar o PCF, podias dar opção de usar o GPIO do buzzer para uma bomba, e já que, normalmente só se usam duas resistências no sistema de três panelas, eliminar um SSR e passar o GPIO para uma terceira bomba.
