### ISSUE TITLE
Comportamento estranho do LCD

### ISSUE THREAD

**Issue by perlporter** [uncodead/BrewUNO#61]
Meu LCD está com este comportamento estranho.
Liga fica tudo OK, ai do nada começa a aparecer caracteres estranhos.

Alguém tem alguma dica do que pode ser ?

![IMG_5651](https://user-images.githubusercontent.com/4180994/91565412-8c446180-e918-11ea-83fa-18a0fc6816e4.jpg)

**Comment by sylvioavilla1** [comment]
Fala @perlporter , beleza?

O meu aconteceu isso também! Parece que no meu caso é pq o meu conector não está muito bem feito, ai ele da um mal contato e da esse erro! Vou refazer tudo e ver se continua.

**Comment by perlporter** [comment]
Exatemente @sylvioavilla1 .. mas no Bmex não apresenta este "problema"... mas parece que algo relacionado ao controlador do LCD, o @dumpamob já está vendo isso :-)

**Comment by ahsolda** [comment]
Também tenho esse problema. Alguma novidade quanto a resolução?

**Comment by felipeserta** [comment]
no bmex realmente no meu painel ou foi temperatura alta ou mal contato, montei com um sensor monitorando a temperatura do painel e fiz uma logica de intertravamento. Estou esperando chegar mais pecas para montar um prototipo do Brew-uno mto legal a interface parece um pouco a do Craftbeerpi

**Comment by uncodead** [comment]
Ta com cara de mal contato. Isso não é normal no LCD. Refaz as ligações e tenta novamente. No limite troca o LCD/ESP8266. 

Abs

**Comment by dumpamob** [comment]
> 
> 
> Fala @perlporter , beleza?
> 
> O meu aconteceu isso também! Parece que no meu caso é pq o meu conector não está muito bem feito, ai ele da um mal contato e da esse erro! Vou refazer tudo e ver se continua.
> 
> Por curiosidade, qual placa está usando? Mazza?

O caso do @perlporter é que o controlador do LCD dele não é o HD44780 (Hitachi, mais comum), o dele é usa o S6A0069 (Samsung), tem que ver se o seu LCD usa esse controlador também, em teoria ele deveria ser compatível pois é um clone do HD44780, mas é só teoria. 
 @ahsolda e @felipeserta vejam também qual é o LCD de vocês, deve ter algum adesivo com algum código na parte de trás e informem. Se for o LCD padrão possivelmente é algum problema nos conectores, na solda...

![WhatsApp Image 2020-09-25 at 11 11 27](https://user-images.githubusercontent.com/34325697/94279399-6d8ab800-ff22-11ea-9f04-3f652e8187d7.jpeg)

**Comment by uncodead** [comment]
Valew dumpa! Fechando a issue
