### ISSUE TITLE
ESP8266 reboots when it is not able to reach NTP server.

### ISSUE THREAD

**Issue by danielht83** [uncodead/BrewUNO#93]
If NTP server is not reached (bad NTP server address is defined on settings), ESP8266 reboots when I try to start the boil or go to the next mash step.

I'm using the simple wiring assembly (wihtout LCD and buttons).

**Comment by eladisimo** [comment]
did you get it solved?

**Comment by uncodead** [comment]
try ou an other esp. can you post the recipe?

**Comment by eladisimo** [comment]
Not sure what the recipe is. I've replaced the wires to thinner ones and
the problem disappeared.
Not sure why and how its related. I'm guessing too much impedance on the
line caused IR drop that led to resets.

**Comment by eladisimo** [comment]
Hi, i've replaced all the cables with thinner dupont wires and the problem
was solved.
I also changes the fw burning tool to to BrewFlasher 1.5 which is way more
reliable than the original tool.

Lets me know if that helps.


₪ 2.16  26%OFF | Dupont Line 10CM 20CM 30CM 40Pin Male to Male + Male to
Female and Female to Female Jumper Wire Dupont Cable for Arduino DIY KIT
https://a.aliexpress.com/_EGpg9Td
