### ISSUE TITLE
importar Json do brewfather

### ISSUE THREAD

**Issue by ropinho1312** [uncodead/BrewUNO#99]
Bom Dia Bruno,  compre a versão Pro do Brewuno e tenho a versão grátis do brewfather e nele tem uma opção de vc exportar a receita em json porem no pro vc não consegue importar esta receita em json, seria possível implantar esta importação?
desde já agradeço e parabenizo pelo projeto!!!

**Comment by uncodead** [comment]
vc precisa gerar a chave do bf e configurar no brewuno
